name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Pipeline berjalan setiap ada perubahan di branch `master`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ranmits10 -f ./.github/workflows/DockerFile .

      # Step 3: Save Docker Image to tarball
      - name: Save Docker Image
        run: |
          docker save -o ranmits10.tar ranmits10

      # Step 4: Upload Docker Image Artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ranmits10-image
          path: ranmits10.tar

  analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up JDK
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Update ke Java 17

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Menunggu proses build selesai

    steps:
      # Step 1: Download Docker Image Artifact
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: ranmits10-image

      # Step 2: Upload Artifact to EC2
      - name: SSH to EC2 and Prepare Deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu  # Username Anda
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Buat direktori untuk upload file jika belum ada
            mkdir -p ~/docker-images/

            # Pastikan tidak ada tarball lama
            rm -f ~/docker-images/ranmits10.tar

      # Step 3: Upload Docker Tarball
      - name: Upload Docker Tarball
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ranmits10.tar
          target: ~/docker-images/


      # Step 4: Load Docker Image and Deploy
      - name: SSH to EC2 and Deploy Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu  # Username Anda
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Load Docker Image
            docker load -i ~/docker-images/ranmits10.tar

            # Stop dan Remove container lama jika ada
            docker stop ranmits10-container || true
            docker rm ranmits10-container || true

            # Jalankan container baru
            docker run -d --name ranmits10-container -p 9000:9000 ranmits10

            # Bersihkan file tarball untuk menghemat ruang
            rm -f ~/docker-images/ranmits10.tar
