name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Build Docker Image
        run: docker build deceitfull/fpso_kel10 .
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Image to DockerHub
        run: docker push deceitfull/fpso_kel10:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image
        run: docker pull deceitfull/fpso_kel10
      - name: Delete old container
        run: docker rm -f ranmits-container
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name ranmits-container deceitfull/fpso_kel10
