name: CI/CD Pipeline
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - name: Create .env file
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Run tests
        run: php artisan test
      - name: Build Docker Image
        run: docker build -t deceitfull/fpso_kel10
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Image to DockerHub
        run: docker push deceitfull/fpso_kel10:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@52.64.199.117 && docker pull deceitfull/fpso_kel10
      - name: Stop and Delete old container
        run: docker stop ranmits-container && docker rm ranmits-container
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name ranmits-container deceitfull/fpso_kel10
